In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex=pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open('models/ohe_embarked.pkl','rb'))
clf=pickle.load(open('models/clf.pkl','rb'))

In [43]:
# Assume user input
# Pclass/sex/age/SibSp/Parch/Fare/Embarked
test_input=np.array([3,'male',80,0,0,0.5,'C'],dtype=object).reshape(1,7)

In [44]:
test_input

array([[3, 'male', 80, 0, 0, 0.5, 'C']], dtype=object)

In [45]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\shubh\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [46]:
test_input_sex

array([[0., 1.]])

In [47]:
test_input_embarked=ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [48]:
test_input_embarked

array([[1., 0., 0.]])

In [49]:
test_input_age=test_input[:,2].reshape(1,1)
test_input_age

array([[80]], dtype=object)

In [50]:
# Pclass/sex/age/SibSp/Parch/Fare/Embarked
test_input_remain=test_input[:,[0,3,4,5]].reshape(1,4)

In [51]:
test_input_transformed=np.concatenate((test_input_remain,test_input_age,test_input_sex,test_input_embarked),axis=1)

In [52]:
test_input_transformed.shape

(1, 10)

In [53]:
clf.predict(test_input_transformed)

array([0], dtype=int64)